# Generated by Django 5.1.5 on 2025-02-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glassblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
